title: I, J3RN
email: jonarnett90@gmail.com
description:
  The J3RNAL: Thoughts, ideas, projects, and commentary by J3RN.
baseurl: ""
url: "http://i.j3rn.com" # the base hostname & protocol for your site
twitter_username: _J3RN
github_username:  J3RN

# Build settings
markdown: kramdown
